apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: wfokvz4my-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/wfokvz4my-java-quarkus-gitops